version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  back:
    container_name: back
    build: ./back
    ports:
      - '4000:4000'
    links:
      - mongo
  front:
    container_name: front
    build: ./front
    ports:
      - '3000:3000'
    volumes:
      - ./front:/front