FROM node:latest
RUN mkdir -p /usr/src/app
RUN npm install -g nodemon
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm install && mv /usr/src/app/node_modules /node_modules
COPY . /usr/src/app
EXPOSE 4000
CMD [ "nodemon" ]
